### ISSUE TITLE
Strange effect in eclipse if classpath contains jar's with "invalid" INDEX.LIST

### ISSUE THREAD

**Issue by ahoehma** [testng-team/testng-remote#29] opened 2016-07-15 09:11 UTC
When I start testng test (6.9.11) with eclipse debugger the first "stop" is always in the sun.misc.URLClassPath$JarLoader.getJarFile(java.net.URL) line: 891 ... with (Suspended (exception java.io.FileNotFoundException))

```
Thread [main] (Suspended (exception java.io.FileNotFoundException))	
	sun.misc.URLClassPath$JarLoader.getJarFile(java.net.URL) line: 891	
	sun.misc.URLClassPath$JarLoader.access$700(sun.misc.URLClassPath$JarLoader, java.net.URL) line: 756	
	sun.misc.URLClassPath$JarLoader$1.run() line: 838	
	sun.misc.URLClassPath$JarLoader$1.run() line: 831	
	java.security.AccessController.doPrivileged(java.security.PrivilegedExceptionAction<T>) line: not available [native method]	
	sun.misc.URLClassPath$JarLoader.ensureOpen() line: 830	
	sun.misc.URLClassPath$JarLoader.<init>(java.net.URL, java.net.URLStreamHandler, java.util.HashMap<java.lang.String,sun.misc.URLClassPath.Loader>) line: 803	
	sun.misc.URLClassPath$JarLoader$3.run() line: 1057	
	sun.misc.URLClassPath$JarLoader$3.run() line: 1054	
	java.security.AccessController.doPrivileged(java.security.PrivilegedExceptionAction<T>) line: not available [native method]	
	sun.misc.URLClassPath$JarLoader.getResource(java.lang.String, boolean, java.util.Set<java.lang.String>) line: 1053	
	sun.misc.URLClassPath$JarLoader.getResource(java.lang.String, boolean) line: 1013	
	sun.misc.URLClassPath$JarLoader.findResource(java.lang.String, boolean) line: 983	
	sun.misc.URLClassPath$1.next() line: 240 [local variables unavailable]	
	sun.misc.URLClassPath$1.hasMoreElements() line: 250	
	java.net.URLClassLoader$3$1.run() line: 601	
	java.net.URLClassLoader$3$1.run() line: 599	
	java.security.AccessController.doPrivileged(java.security.PrivilegedAction<T>, java.security.AccessControlContext) line: not available [native method]	
	java.net.URLClassLoader$3.next() line: 598	
	java.net.URLClassLoader$3.hasMoreElements() line: 623	
	sun.misc.CompoundEnumeration.next() line: 45	
	sun.misc.CompoundEnumeration.hasMoreElements() line: 54 [local variables unavailable]	
	java.util.ServiceLoader$LazyIterator.hasNextService() line: 354	
	java.util.ServiceLoader$LazyIterator.hasNext() line: 393	
	java.util.ServiceLoader$1.hasNext() line: 474	
	org.testng.remote.support.ServiceLoaderHelper.getFirst(org.osgi.framework.Version) line: 16	
	org.testng.remote.RemoteTestNG.main(java.lang.String[]) line: 43	
```

The missing jar is (I have multiple - for example) ... 

I see that the "mising" jar is "file:/D:/Dev/ApacheMaven/repository/com/vaadin/addon/vaadin-charts/3.0.0/jackson-databind-2.5.2.jar" ... this file can't exists ... I guess the INDEX.LIST from the vaadin-chart-addon 3.0.0 cause this problem (but I have other jar with the same problem *g*).

Here is the content of the INDEX.LIST:

```
JarIndex-Version: 1.0
 
vaadin-charts-3.0.0.jar
META-INF
META-INF/maven
META-INF/maven/com.vaadin.addon
META-INF/maven/com.vaadin.addon/vaadin-charts
com
com/vaadin
com/vaadin/addon
com/vaadin/addon/charts
com/vaadin/addon/charts/client
com/vaadin/addon/charts/client/ui
com/vaadin/addon/charts/declarative
com/vaadin/addon/charts/events
com/vaadin/addon/charts/model
com/vaadin/addon/charts/model/serializers
com/vaadin/addon/charts/shared
com/vaadin/addon/charts/themes
com/vaadin/addon/charts/util
com/vaadin/ui
com/vaadin/ui/declarative
 
vaadin-charts-model-3.0.0.jar
META-INF/maven
META-INF/maven/com.vaadin.addon
META-INF/maven/com.vaadin.addon/vaadin-charts-model
com
com/vaadin
com/vaadin/addon
com/vaadin/addon/charts
com/vaadin/addon/charts/model
com/vaadin/addon/charts/model/style
com/vaadin/addon/charts/util
 
jackson-annotations-2.5.0.jar
META-INF
META-INF/maven
META-INF/maven/com.fasterxml.jackson.core
META-INF/maven/com.fasterxml.jackson.core/jackson-annotations
com
com/fasterxml
com/fasterxml/jackson
com/fasterxml/jackson/annotation
 
jackson-databind-2.5.2.jar
META-INF
META-INF/maven
META-INF/maven/com.fasterxml.jackson.core
META-INF/maven/com.fasterxml.jackson.core/jackson-databind
META-INF/services
com
com/fasterxml
com/fasterxml/jackson
com/fasterxml/jackson/databind
com/fasterxml/jackson/databind/annotation
com/fasterxml/jackson/databind/cfg
com/fasterxml/jackson/databind/deser
com/fasterxml/jackson/databind/deser/impl
com/fasterxml/jackson/databind/deser/std
com/fasterxml/jackson/databind/exc
com/fasterxml/jackson/databind/ext
com/fasterxml/jackson/databind/introspect
com/fasterxml/jackson/databind/jsonFormatVisitors
com/fasterxml/jackson/databind/jsonschema
com/fasterxml/jackson/databind/jsontype
com/fasterxml/jackson/databind/jsontype/impl
com/fasterxml/jackson/databind/module
com/fasterxml/jackson/databind/node
com/fasterxml/jackson/databind/ser
com/fasterxml/jackson/databind/ser/impl
com/fasterxml/jackson/databind/ser/std
com/fasterxml/jackson/databind/type
com/fasterxml/jackson/databind/util
 
jackson-core-2.5.1.jar
META-INF
META-INF/maven
META-INF/maven/com.fasterxml.jackson.core
META-INF/maven/com.fasterxml.jackson.core/jackson-core
META-INF/services
com
com/fasterxml
com/fasterxml/jackson
com/fasterxml/jackson/core
com/fasterxml/jackson/core/base
com/fasterxml/jackson/core/format
com/fasterxml/jackson/core/io
com/fasterxml/jackson/core/json
com/fasterxml/jackson/core/sym
com/fasterxml/jackson/core/type
com/fasterxml/jackson/core/util
 
commons-io-1.4.jar
META-INF
META-INF/maven
META-INF/maven/commons-io
META-INF/maven/commons-io/commons-io
org
org/apache
org/apache/commons
org/apache/commons/io
org/apache/commons/io/comparator
org/apache/commons/io/filefilter
org/apache/commons/io/input
org/apache/commons/io/output
```

**Comment by missedone** [comment] 2016-07-15 09:45
hi @ahoehma
could you update your plugin to latest release version 6.9.12.201607091356, and let me know how is that going then?
thanks

**Comment by ahoehma** [comment] 2016-07-29 09:56
@missedone  please tell me where is the update site for the latest testng-eclipse?

**Comment by ahoehma** [comment] 2016-07-29 10:03
Same effect with latest beta 6,9,13

**Comment by missedone** [comment] 2016-07-29 10:47
could you paste the error trace here (i expected it's diff from the previous one).
thanks

**Comment by missedone** [comment] 2016-07-29 10:47
also, if it's possible, could you share a sample project for reproducing this issue?

**Comment by missedone** [comment] 2016-07-29 12:12
hmm, looks like INDEX.LIST messed up java.util.ServiceLoader, i do not see any solution yet.

**Comment by juherr** [comment] 2016-07-29 12:23
@missedone maybe ServiceLoader should be replaced by osgi mechanism?

**Comment by missedone** [comment] 2016-07-29 12:44
@juherr , my search on 'ServiceLoader alternatives' also pointed me to OSGi 😄 , but my concern is it's sort of overkill for us

**Comment by juherr** [comment] 2016-07-29 12:49
In fact, as Eclipse is OSGI based, I suppose it could help to fix the issue.

But clearly, from testng-remote point of view, it is overkill!

**Comment by missedone** [comment] 2016-07-29 13:07
hi @ahoehma
i'm wondering is everything working fine if you run test on command cli (for example, if your project is maven managed, run `mvn -e test`)

**Comment by ahoehma** [comment] 2016-07-29 18:48
@missedone  mvn test is only "running" the tests and not debugging it ... I think the "exception" is catched/ignored somewhere.

**Comment by juherr** [comment] 2016-07-29 18:53
Surefire is not using testng-remote.

**Comment by missedone** [comment] 2016-07-30 00:11
yes, I know. i was asking because, it just want to make sure the test works without testng-remote.
so in the PR #30 , i make ServiceLoader to return immediately once it detects one RemoteTestNGFactory (rather than scan all Jar on the classpath), this is with an assumption that testng-remote is on front of any jars contains INDEX.LIST (which is true in TestNG eclipse plugin).
i have no env to verify this, but hopefully this workaround can work

**Comment by missedone** [comment] 2016-07-31 15:23
@ahoehma 
could you have a try with the latest beta 6.9.13.x of TestNG Eclipse Plugin, hope the workaround work for the case of invalid INDEX.LIST

**Comment by ahoehma** [comment] 2016-07-31 18:14
@missedone  yep ... tomorrow at work I will try it :+1:

**Comment by ahoehma** [comment] 2016-08-05 06:49
@missedone  seems to work now :)

  TestNG	6.9.13.201607312305	org.testng.eclipse.feature.group	Cedric Beust
  TestNG M2E Integration (Optional)	6.9.13.201607312305	org.testng.eclipse.maven.feature.feature.group	TestNG Team

**Comment by missedone** [comment] 2016-08-05 06:59
cool, i'm closing this now.
feel free to re-open it if you still encounter the issue.
thanks

**Closed by missedone** 2016-08-05 06:59 UTC
